"use client";
import { FormEvent,useEffect,useState } from "react";
import { createClient,Session } from "@supabase/supabase-js";
const supabase=createClient("https://wvmsylpqvaiqtvtkrxil.supabase.co","sb_publishable_IVZ-ENHIfzPfuo-EDoRfuA_80t98jJ5");
type Shop={id:string;owner_id:string;name:string;slug:string;whatsapp:string|null;address:string|null;logo_url:string|null;is_open:boolean;latitude?:number|null;longitude?:number|null};
type Barber={id:string;name:string;is_active:boolean};type Service={id:string;name:string;price:number;duration_minutes:number;is_active:boolean};
type Queue={id:string;customer_name:string;status:string;joined_at:string;service_id:string;barber_id:string|null};
export default function Admin(){
 const[session,setSession]=useState<Session|null>(null),[shop,setShop]=useState<Shop|null>(null),[barbers,setBarbers]=useState<Barber[]>([]),[services,setServices]=useState<Service[]>([]),[queue,setQueue]=useState<Queue[]>([]),[contacts,setContacts]=useState<Record<string,string>>({}),[menu,setMenu]=useState(false),[settings,setSettings]=useState(false),[busy,setBusy]=useState(true),[authError,setAuthError]=useState("");
 useEffect(()=>{void (async()=>{const{data}=await supabase.auth.getSession();if(data.session){setSession(data.session);setBusy(false);return}const r=await supabase.auth.signInAnonymously();if(r.error)setAuthError("Não foi possível iniciar o acesso automático. Ative Anonymous Sign-Ins no Supabase.");setSession(r.data.session);setBusy(false)})();const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)void loadShop();else setShop(null)},[session?.user.id]);
 useEffect(()=>{if(!shop)return;void loadAll();const ch=supabase.channel(`admin-${shop.id}`).on("postgres_changes",{event:"*",schema:"public",table:"queue_entries",filter:`shop_id=eq.${shop.id}`},()=>void loadQueue()).subscribe();return()=>{void supabase.removeChannel(ch)}},[shop?.id]);
 async function loadShop(){setBusy(true);const{data}=await supabase.from("barbershops").select("*").eq("owner_id",session!.user.id).maybeSingle();setShop(data);setBusy(false)}
 async function loadAll(){await Promise.all([loadQueue(),loadBarbers(),loadServices()])}
 async function loadQueue(){if(!shop)return;const[{data:q},{data:c}]=await Promise.all([supabase.from("queue_entries").select("*").eq("shop_id",shop.id).in("status",["waiting","called","in_service"]).order("joined_at"),supabase.from("queue_contacts").select("queue_entry_id,phone").eq("shop_id",shop.id)]);setQueue(q??[]);setContacts(Object.fromEntries((c??[]).map(x=>[x.queue_entry_id,x.phone])))}
 async function loadBarbers(){if(!shop)return;const{data}=await supabase.from("barbers").select("*").eq("shop_id",shop.id).order("name");setBarbers(data??[])}
 async function loadServices(){if(!shop)return;const{data}=await supabase.from("services").select("*").eq("shop_id",shop.id).order("name");setServices(data??[])}
 if(busy)return <main className="adminCenter"><div className="loader"/><p>Preparando sua barbearia...</p></main>;
 if(!session)return <main className="adminCenter"><div className="onboarding"><span className="brand">Fila Fácil</span><h1>Acesso automático indisponível</h1><p>{authError||"Tentando conectar novamente…"}</p><button onClick={()=>location.reload()}>Tentar novamente</button></div></main>;
 if(!shop)return <OnboardingWithLocation userId={session.user.id} onDone={loadShop}/>;
 const publicLink=`https://fila-facil-cast-prods-online.andrey800211.chatgpt.site/?shop=${shop.slug}`;
 return <main className="adminApp"><header className="adminHeader"><div><span className="brand">Fila Fácil</span><h1>{shop.name}</h1><p>Painel da fila • sincronizado ao vivo</p></div><button className="dots" onClick={()=>setMenu(!menu)}>•••</button>{menu&&<div className="menu"><button onClick={()=>{setSettings(!settings);setMenu(false)}}>⚙ Configurações</button><button onClick={()=>void navigator.clipboard.writeText(publicLink)}>🔗 Copiar link público</button></div>}</header>
 <section className="adminStats"><article><span>Fila atual</span><strong>{queue.length}</strong></article><article><span>Espera estimada</span><strong>{queue.reduce((n,q)=>n+(services.find(s=>s.id===q.service_id)?.duration_minutes??30),0)} min</strong></article></section>
 <section className="controlBar"><div><span>Status da fila</span><b>{shop.is_open?"Recebendo clientes":"Fila pausada"}</b></div><button className={shop.is_open?"danger":"success"} onClick={async()=>{await supabase.from("barbershops").update({is_open:!shop.is_open}).eq("id",shop.id);setShop({...shop,is_open:!shop.is_open})}}>{shop.is_open?"Pausar fila":"Abrir fila"}</button></section>
 {settings&&<><ShopProfile shop={shop} onSaved={loadShop}/><Settings shop={shop} barbers={barbers} services={services} publicLink={publicLink} refresh={loadAll}/></>}
 <section className="adminQueue"><div className="adminTitle"><div><span>Atendimentos</span><h2>Fila de agora</h2></div><i/></div>{queue.length===0?<div className="empty">Nenhum cliente esperando ✨</div>:queue.map((q,i)=>{const s=services.find(x=>x.id===q.service_id),b=barbers.find(x=>x.id===q.barber_id),phone=contacts[q.id];return <article className="adminRow" key={q.id}><b>{i+1}</b><div className="client"><strong>{q.customer_name}</strong><span>{s?.name??"Serviço"}{b?` • ${b.name}`:" • Primeiro disponível"}</span>{phone&&<a href={`https://wa.me/55${phone.replace(/\D/g,"")}`} target="_blank">WhatsApp {phone}</a>}</div><div className="rowActions">{q.status!=="in_service"&&<button onClick={()=>void updateStatus(q.id,"in_service")}>Chamar</button>}<button className="finish" onClick={()=>void updateStatus(q.id,"finished")}>Finalizar</button></div></article>})}</section>
 <section className="shareCard"><span>Link para seus clientes</span><h2>{shop.slug}</h2><p>Coloque este link na bio, envie pelo WhatsApp ou transforme em QR Code.</p><button onClick={()=>void navigator.clipboard.writeText(publicLink)}>Copiar link público</button></section>
 </main>;
 async function updateStatus(id:string,status:string){await supabase.from("queue_entries").update({status,[status==="in_service"?"started_at":"finished_at"]:new Date().toISOString()}).eq("id",id);await loadQueue()}
}
function Onboarding({userId,onDone}:{userId:string;onDone:()=>void}){const[name,setName]=useState(""),[slug,setSlug]=useState(""),[whatsapp,setWhatsapp]=useState(""),[address,setAddress]=useState(""),[error,setError]=useState("");async function go(e:FormEvent){e.preventDefault();const clean=slug.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-");const{error}=await supabase.from("barbershops").insert({owner_id:userId,name,slug:clean,whatsapp,address});if(error)setError(error.message);else onDone()}return <main className="adminCenter"><form className="onboarding" onSubmit={go}><span className="brand">Primeira configuração</span><h1>Monte sua barbearia</h1><p>Você poderá alterar tudo depois pelo menu.</p><label>Nome da barbearia<input value={name} onChange={e=>{setName(e.target.value);setSlug(e.target.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"))}} required/></label><label>Código do link<input value={slug} onChange={e=>setSlug(e.target.value)} required minLength={4}/></label><label>WhatsApp da barbearia<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} required/></label><label>Endereço<input value={address} onChange={e=>setAddress(e.target.value)}/></label><button>Criar painel</button>{error&&<div className="notice error">{error}</div>}</form></main>}
function Settings({shop,barbers,services,publicLink,refresh}:{shop:Shop;barbers:Barber[];services:Service[];publicLink:string;refresh:()=>Promise<void>}){const[barber,setBarber]=useState(""),[service,setService]=useState(""),[price,setPrice]=useState(""),[duration,setDuration]=useState("30");return <section className="settingsPanel"><h2>Configurações</h2><p>Cadastre sua própria equipe e seus serviços.</p><div className="settingGrid"><form onSubmit={async e=>{e.preventDefault();await supabase.from("barbers").insert({shop_id:shop.id,name:barber});setBarber("");await refresh()}}><h3>Novo barbeiro</h3><input value={barber} onChange={e=>setBarber(e.target.value)} placeholder="Nome do barbeiro" required/><button>Adicionar</button><ul>{barbers.map(b=><li key={b.id}>{b.name}<button type="button" onClick={async()=>{await supabase.from("barbers").update({is_active:!b.is_active}).eq("id",b.id);await refresh()}}>{b.is_active?"Ativo":"Pausado"}</button></li>)}</ul></form><form onSubmit={async e=>{e.preventDefault();await supabase.from("services").insert({shop_id:shop.id,name:service,price:Number(price),duration_minutes:Number(duration)});setService("");setPrice("");await refresh()}}><h3>Novo serviço</h3><input value={service} onChange={e=>setService(e.target.value)} placeholder="Ex.: Corte degradê" required/><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Preço" required/><input value={duration} onChange={e=>setDuration(e.target.value)} inputMode="numeric" placeholder="Minutos" required/><button>Adicionar</button><ul>{services.map(s=><li key={s.id}>{s.name} • R$ {Number(s.price).toFixed(2)}<button type="button" onClick={async()=>{await supabase.from("services").update({is_active:!s.is_active}).eq("id",s.id);await refresh()}}>{s.is_active?"Ativo":"Pausado"}</button></li>)}</ul></form></div><div className="linkBox">{publicLink}</div></section>}

function OnboardingWithLocation({userId,onDone}:{userId:string;onDone:()=>void}){
 const[name,setName]=useState(""),[slug,setSlug]=useState(""),[whatsapp,setWhatsapp]=useState(""),[address,setAddress]=useState(""),[coords,setCoords]=useState<{latitude:number;longitude:number}|null>(null),[error,setError]=useState("");
 function locate(){navigator.geolocation.getCurrentPosition(p=>setCoords({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>setError("Não foi possível obter a localização. Tente novamente."),{enableHighAccuracy:true})}
 async function go(e:FormEvent){e.preventDefault();const clean=slug.toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-");const{error}=await supabase.from("barbershops").insert({owner_id:userId,name,slug:clean,whatsapp,address,...(coords??{})});if(error)setError(error.message);else onDone()}
 return <main className="adminCenter"><form className="onboarding" onSubmit={go}><span className="brand">Modo barbeiro</span><h1>Cadastre sua barbearia</h1><p>Essas informações aparecerão no catálogo para seus clientes.</p><label>Nome da barbearia<input value={name} onChange={e=>{setName(e.target.value);setSlug(e.target.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"))}} required/></label><label>Código do link<input value={slug} onChange={e=>setSlug(e.target.value)} required minLength={4}/></label><label>WhatsApp da barbearia<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} required/></label><label>Endereço completo<input value={address} onChange={e=>setAddress(e.target.value)} required/></label><button type="button" className="locationButton" onClick={locate}>{coords?"✓ Localização salva":"⌖ Usar localização atual"}</button><button>Criar painel</button>{error&&<div className="notice error">{error}</div>}</form></main>
}

function ShopProfile({shop,onSaved}:{shop:Shop;onSaved:()=>Promise<void>}){
 const[name,setName]=useState(shop.name),[address,setAddress]=useState(shop.address??""),[whatsapp,setWhatsapp]=useState(shop.whatsapp??""),[logo,setLogo]=useState(shop.logo_url??""),[notice,setNotice]=useState("");
 async function save(e:FormEvent){e.preventDefault();const{error}=await supabase.from("barbershops").update({name,address,whatsapp,logo_url:logo||null}).eq("id",shop.id);setNotice(error?error.message:"Barbearia atualizada com sucesso!");if(!error)await onSaved()}
 return <section className="settingsPanel"><h2>🏪 Perfil da barbearia</h2><p>Deixe seu perfil bonito e completo para chamar a atenção dos clientes.</p><form className="profileForm" onSubmit={save}>{logo&&<img className="logoPreview" src={logo} alt="Prévia da barbearia"/>}<label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Endereço<input value={address} onChange={e=>setAddress(e.target.value)} required/></label><label>WhatsApp<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} required/></label><label>Foto da barbearia<input value={logo} onChange={e=>setLogo(e.target.value)} placeholder="Cole aqui o link da foto"/></label><button>💾 Salvar alterações</button>{notice&&<div className="notice">{notice}</div>}</form></section>
}
