"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient("https://wvmsylpqvaiqtvtkrxil.supabase.co","sb_publishable_IVZ-ENHIfzPfuo-EDoRfuA_80t98jJ5");
type Shop={id:string;name:string;slug:string;address:string|null;logo_url:string|null;is_open:boolean;latitude?:number|null;longitude?:number|null};
type Service={id:string;name:string;price:number;duration_minutes:number};type Barber={id:string;name:string};type QueueItem={id:string;customer_name:string;status:string;joined_at:string;service_id:string;barber_id:string|null};
type Pos={lat:number;lng:number};
const distance=(a:Pos,b:Pos)=>{const r=6371,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))};

export default function Home(){
 const[mode,setMode]=useState<"choose"|"client">("choose"),[shops,setShops]=useState<Shop[]>([]),[search,setSearch]=useState(""),[position,setPosition]=useState<Pos|null>(null),[geoMsg,setGeoMsg]=useState("");
 const[shop,setShop]=useState<Shop|null>(null),[services,setServices]=useState<Service[]>([]),[barbers,setBarbers]=useState<Barber[]>([]),[queue,setQueue]=useState<QueueItem[]>([]),[name,setName]=useState(""),[serviceId,setServiceId]=useState(""),[barberId,setBarberId]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{const slug=new URLSearchParams(location.search).get("shop");if(slug){setMode("client");void openShop(slug)}},[]);
 useEffect(()=>{if(mode==="client"&&!shop)void loadDirectory()},[mode,shop]);
 useEffect(()=>{if(!shop)return;const channel=supabase.channel(`queue-${shop.id}`).on("postgres_changes",{event:"*",schema:"public",table:"queue_entries",filter:`shop_id=eq.${shop.id}`},()=>void refreshQueue(shop.id)).on("postgres_changes",{event:"UPDATE",schema:"public",table:"barbershops",filter:`id=eq.${shop.id}`},()=>void refreshShop(shop.slug)).subscribe();return()=>{void supabase.removeChannel(channel)}},[shop?.id]);
 const wait=useMemo(()=>queue.reduce((n,q)=>n+(services.find(s=>s.id===q.service_id)?.duration_minutes??30),0),[queue,services]);
 const visible=useMemo(()=>shops.filter(s=>(s.name+" "+(s.address??"")).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>{if(a.is_open!==b.is_open)return a.is_open?-1:1;if(position&&a.latitude&&a.longitude&&b.latitude&&b.longitude)return distance(position,{lat:a.latitude,lng:a.longitude})-distance(position,{lat:b.latitude,lng:b.longitude});return a.name.localeCompare(b.name)}),[shops,search,position]);
 async function loadDirectory(){setLoading(true);const{data}=await supabase.from("barbershops").select("*").order("name");setShops((data??[]) as Shop[]);setLoading(false)}
 function locate(){setGeoMsg("Buscando sua localização…");navigator.geolocation.getCurrentPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude});setGeoMsg("Ordenado pelas mais próximas")},()=>setGeoMsg("Não foi possível acessar o GPS. Você ainda pode pesquisar pelo nome."),{enableHighAccuracy:true,timeout:12000})}
 async function refreshShop(slug:string){const{data}=await supabase.from("barbershops").select("*").eq("slug",slug).maybeSingle();if(data)setShop(data as Shop)}
 async function refreshQueue(id:string){const{data}=await supabase.from("queue_entries").select("id,customer_name,status,joined_at,service_id,barber_id").eq("shop_id",id).in("status",["waiting","called","in_service"]).order("joined_at");setQueue(data??[])}
 async function openShop(slug:string){setLoading(true);setMessage("");const{data}=await supabase.from("barbershops").select("*").eq("slug",slug).maybeSingle();if(!data){setMessage("Barbearia não encontrada.");setLoading(false);return}setShop(data as Shop);const[sr,br]=await Promise.all([supabase.from("services").select("id,name,price,duration_minutes").eq("shop_id",data.id).eq("is_active",true).order("name"),supabase.from("barbers").select("id,name").eq("shop_id",data.id).eq("is_active",true).order("name")]);setServices(sr.data??[]);setBarbers(br.data??[]);setServiceId(sr.data?.[0]?.id??"");await refreshQueue(data.id);history.replaceState({},"",`?shop=${encodeURIComponent(slug)}`);setLoading(false)}
 async function join(e:FormEvent){e.preventDefault();if(!shop||!serviceId)return;setLoading(true);const{error}=await supabase.rpc("join_public_queue",{p_shop_slug:shop.slug,p_customer_name:name,p_phone:"",p_service_id:serviceId,p_barber_id:barberId||null});setMessage(error?error.message:"Você entrou na fila! Acompanhe sua posição nesta tela.");if(!error){setName("");await refreshQueue(shop.id)}setLoading(false)}

 if(mode==="choose")return <main className="landing"><div className="landingShade"/><section className="entryCard roleCard"><span className="brand">Fila Fácil</span><h1>Bem-vindo</h1><div className="roleGrid"><button onClick={()=>location.href="/admin"}><b>✂ Cadastrar barbearia</b></button><button onClick={()=>setMode("client")}><b>✦ Sou cliente</b></button></div></section></main>;
 if(!shop)return <main className="directory"><header className="directoryHero"><button className="back" onClick={()=>setMode("choose")}>←</button><span className="brand">Modo cliente</span><h1>Encontre sua barbearia</h1><p>Veja fotos, localização e quem está atendendo. Entre na fila em poucos segundos.</p></header><section className="directoryTools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome ou endereço"/><button onClick={locate}>📍 Usar minha localização</button>{geoMsg&&<small>{geoMsg}</small>}</section><section className="shopList"><div className="directoryTitle"><div><span>Disponíveis agora</span><h2>Barbearias</h2></div><b>{visible.length}</b></div>{loading?<div className="empty">Carregando barbearias…</div>:visible.length===0?<div className="empty">Nenhuma barbearia cadastrada ainda.</div>:visible.map(s=>{const km=position&&s.latitude&&s.longitude?distance(position,{lat:s.latitude,lng:s.longitude}):null;return <button className="shopCard" key={s.id} onClick={()=>void openShop(s.slug)}>{s.logo_url?<img className="shopAvatar photo" src={s.logo_url} alt={`Foto da ${s.name}`}/>:<div className="shopAvatar">✂</div>}<div><strong>{s.name}</strong><span>📍 {s.address||"Endereço não informado"}</span>{km!==null&&<em>{km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1)} km`} de você</em>}</div><i className={s.is_open?"open":"closed"}>{s.is_open?"Aberta":"Fechada"}</i></button>})}</section></main>;
 return <main className="appShell"><header className="shopHeader"><button className="back" onClick={()=>{setShop(null);history.replaceState({},"","/")}}>←</button><div><span className="brand">Fila Fácil</span><h1>{shop.name}</h1><p>{shop.address||"Atendimento por ordem de chegada"}</p></div><span className={shop.is_open?"status open":"status closed"}>{shop.is_open?"Aberta":"Fechada"}</span></header><section className="stats"><article><strong>{queue.length}</strong><span>na fila</span></article><article><strong>{wait} min</strong><span>espera estimada</span></article></section><section className="queuePanel"><div className="sectionTitle"><div><span>Atualização ao vivo</span><h2>Fila agora</h2></div><i/></div>{queue.length===0?<div className="empty">A cadeira está livre ✨</div>:queue.map((q,i)=><article className="queueRow" key={q.id}><b>{i+1}</b><div><strong>{q.customer_name}</strong><span>{services.find(s=>s.id===q.service_id)?.name??"Serviço"}</span></div><em>{q.status==="in_service"?"Atendendo":q.status==="called"?"Chamado":"Aguardando"}</em></article>)}</section><form className="joinCard" onSubmit={join}><span>Modo cliente</span><h2>Entrar na fila</h2>{!shop.is_open&&<div className="notice error">A barbearia está fechada no momento.</div>}<label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Como podemos chamar você?"/></label><label>Serviço<select value={serviceId} onChange={e=>setServiceId(e.target.value)} required><option value="">Escolha</option>{services.map(s=><option value={s.id} key={s.id}>{s.name} • R$ {Number(s.price).toFixed(2).replace(".",",")} • {s.duration_minutes} min</option>)}</select></label>{barbers.length>0&&<label>Preferência de barbeiro<select value={barberId} onChange={e=>setBarberId(e.target.value)}><option value="">Primeiro disponível</option>{barbers.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}<button disabled={loading||!shop.is_open}>{loading?"Confirmando…":"Entrar na fila"}</button>{message&&<div className="notice">{message}</div>}<small>Para entrar, basta informar seu nome.</small></form></main>;
}
